### ISSUE TITLE
标签页DPI有问题

### ISSUE THREAD

**Issue by znlsl** [lily-debug/extab#11]
标签页DPI有问题，特别小，版本1.0.0.22
![image](https://user-images.githubusercontent.com/25316391/116808798-57567180-ab6d-11eb-82a3-089f0b63ada9.png)

![image](https://user-images.githubusercontent.com/25316391/116808754-30983b00-ab6d-11eb-90a6-71504e6b720f.png)

**Comment by halw001** [comment]
刚从clover换过来，也发现对高分辨率/高DPI优化不好

**Comment by lily-debug** [comment]
最新版已兼容
