### ISSUE TITLE
开启DPI缩放后标签页太小

### ISSUE THREAD

**Issue by bdgroup-lab** [lily-debug/extab#14]
操作系统：Windows 10 21H2 LTSC
显示器：27寸
分辨率：4k
DPI缩放：150%
问题：开DPI缩放后，extab标签实在太小，希望能够跟随系统DPI进行缩放。
![QQ截图20211207212551](https://user-images.githubusercontent.com/46755786/145040100-3c02047f-75d7-48f1-9d26-33f35130b4c9.png)
另外，软件和原本资源管理器窗口之间有概率会出现一条空隙，不知道以后会不会修复。
![QQ截图20211207212604](https://user-images.githubusercontent.com/46755786/145040721-ce38a5aa-fa7b-4dd5-abed-49c3c385ab1d.png)

**Comment by bdgroup-lab** [comment]
忘记补充软件版本：1.0.0.42

**Comment by lily-debug** [comment]
150的dpi 正在兼容中

**Comment by lily-debug** [comment]
1.1 已修复
