### ISSUE TITLE
希望能添加一个拖拽复制功能

### ISSUE THREAD

**Issue by CoolLoong** [lily-debug/extab#19]
在检测到一个文件被拖拽到另一个窗口标签上暂停一会后，会智能跳转到该窗口标签
在检测到一个文件被拖拽到另一个窗口标签上会复制到该窗口标签下

**Comment by lily-debug** [comment]
在1.1版本上已添加此功能，拖文件或文件夹到已打开的标签页上复制， 拖到新建标签页按钮右侧，则打开此文件夹。
