### ISSUE TITLE
高分辨率不兼容

### ISSUE THREAD

**Issue by duduGao** [lily-debug/extab#2]
在win10操作系统4k屏的笔记上出现不兼容现象。

**Comment by lily-debug** [comment]
方便传个图看下吗？

**Comment by duduGao** [comment]
![批注 2020-08-09 104852](https://user-images.githubusercontent.com/38971350/89780564-429bfe80-db44-11ea-8ff7-caed4e8e1749.png)
这样的。

**Comment by lily-debug** [comment]
我在升级驱动时出现了你这种问题，字体你改回来了吧，我通过“设置 轻松使用 显示 放大文本 向右拉下点应用，再拉向最左侧再点应用”已经把字体改回来了，再打开Extab问题不复现了。你那每次打开Extab都会出现这种问题吗？

**Comment by duduGao** [comment]
每次启动都会是这个现象，把我的笔记本的分辨率感觉都给重新设置了，显示没以前清晰了。也不知道是哪里导致的，重启电脑就会恢复原样。

**Comment by lily-debug** [comment]
> 每次启动都会是这个现象，把我的笔记本的分辨率感觉都给重新设置了，显示没以前清晰了。也不知道是哪里导致的，重启电脑就会恢复原样。

**Comment by lily-debug** [comment]
你试下这版本： https://www.lanzoux.com/iZ0Zbfm0z6d
你dpi是多少，如果>=200， 可能会有问题。

**Comment by lily-debug** [comment]
新版已兼容高分屏
