### ISSUE TITLE
很多问题

### ISSUE THREAD

**Issue by GodGun968** [lily-debug/extab#21]
win11 x64
1.资源管理器部分功能失效
原版:
![image](https://user-images.githubusercontent.com/67826085/173304750-164330a3-b99d-49fc-890a-08f826a8b7e5.png)
![image](https://user-images.githubusercontent.com/67826085/173304779-f5ad6a17-7a85-420b-9fb1-45486aecbc30.png)
extab:
![image](https://user-images.githubusercontent.com/67826085/173304833-70f6b814-5bfc-4446-8859-9f09d1d0639a.png)
extab未出图片2的选项
2.
当从桌面打开文件夹时,
![image](https://user-images.githubusercontent.com/67826085/173305650-e4c0808a-1753-4f1f-a924-ecca8a85d7f2.png)
此处点击无反应
3.选择其他标签时,再次返回控制面板,上方会被收藏夹挡住 
![image](https://user-images.githubusercontent.com/67826085/173306177-bc3400b4-4c82-4e00-8149-af16d242befd.png)

**Comment by lily-debug** [comment]
1：资源管理器部分功能失效，最新版本已经解决了。
2：第二个是个bug,我修改下，谢谢你的反馈。
