### ISSUE TITLE
在windows10中使用时“选项”按钮会不可选择，listary的“复制文件路径”会失效

### ISSUE THREAD

**Issue by Garfield233333** [lily-debug/extab#26]
系统：win10家庭中文版21H2
extab版本：1.0.0.60

1.使用extab的时候，文件管理器的“查看-选项”呈灰色不可操作状态
2.使用listary时，listary的“特性-动作-复制路径至剪切板“”不生效，没办法选中文件后进行路径复制。但关闭extab之后可以正常使用，应该是extab的问题。
3.新建标签页有时出现无法新建标签页状况，点击加号之后弹出新的标签，但一小会之后就关闭了，一般都是点第二次才能打开

**Comment by lily-debug** [comment]
新版的1.1已经解决这些问题了
