### ISSUE TITLE
Support for translations

### ISSUE THREAD

**Issue by c-sanchez** [lily-debug/extab#4]
It would be nice to have ExTab in other languages.
For now in the current language (which I don't know what it is ;P) it is very difficult for more people to understand any of their options.
![settings page](https://i.ibb.co/2y68TND/settings-page-language.png)
It would be good to have the program at least in English :P

**Comment by lily-debug** [comment]
It only supports Chinese language currently. 
I will add Englsih language in next next version.
Please be patient, thanks.

**Comment by c-sanchez** [comment]
Thanks, also if possible I would like to translate in spanish later :)

**Comment by lily-debug** [comment]
Thank you very, very much for your participation.
I will collect all the text resource  in install, uninstall and main program,
then translate it to  English,  you can translate it to spanish, 
so I can add spanish in extab.
Wow, the extab will support there language,  thanks for your push.
I will send the text resource to you next week.

**Comment by c-sanchez** [comment]
Hi @lily-debug how are you? I'm still waiting :)

**Comment by lily-debug** [comment]
Sorry to keep you waiting.
Below is english resource i have collected.
Thanks.

Tab:
  New tab
  Copy tab
  Add to bookmark
  Show bookmark
  Close tab
  Close right tabs
  Close other tabs

Bookmark:
  Open in new tab
  Open in new window
  Add to bookmark
  Modify 
  Delete
  New folder
  Show bookmark
  Rename
  
Bookmark Dialog:
   Add to bookmark
   Bookmark
   Path
   System folder
   New folder
   OK
   Canceldgsd,  s  
  
Menu:
  Options
  Forum
  Add QQ group
  Add WeiXin group
  About Extab
  Exit
  

Options:
   General
	  AutoRun
	  Show bookmark
	  Background run
	  Go to prarent path when double click blank space
	  New tab when click blank space with ctrl
	  Close tab when double click tab
   
   Mouse Gesture
	   move up when hold down right mouse      Go to parent path
	   move left when hold down right mouse     Backward
	   move right when hold down right mouse     Forward
	   move down when hold down right mouse      New tab
	   move down and right when hold down right mouse      Close tab
	   
Tabskbar notify:
   Open extab
   Options
   Feedback
   Exit
   
Install:
  ExTab Install:
  
  Please don't change path, because already installed.
  AutoRun
  
Uninstall:
  Uninstall   
  Cancel
  Save User Data

**Comment by c-sanchez** [comment]
The mouse gesture lines looks weird, i think I can help you a bit to improve this part :)

> move up when hold down right mouse Go to parent path
> move left when hold down right mouse Backward
> move right when hold down right mouse Forward
> move down when hold down right mouse New tab
> move down and right when hold down right mouse Close tab
```
Hold right click and move mouse Up go to the Parent path
Hold right click and move mouse to the Left to go back one level
Hold right click and move mouse to the Right to go one level forward
Hold right click and move mouse Down to open a new tab
Hold right click and move mouse Down and Right to close the current tab
```

Here are other lines that I suggest you change:
>Go to prarent path when double click blank space
>New tab when click blank space with ctrl
>Close tab when double click tab
```
Double click blank space to go to the parent path
Click blank space + Ctrl key to open a new Tab
Double click a tab to close it
```

>Canceldgsd, s
```
Cancel, s
```

**Comment by c-sanchez** [comment]
Here my Spanish translation :)

```
Pestaña:
Nueva pestaña
Copiar pestaña
Agregar a favoritos
Mostrar favorito
Cerrar pestaña
Cerrar pestañas a la derecha
Cerrar otras pestañas

Favorito:
Abrir en una nueva pestaña
Abrir en una nueva ventana
Agregar a favoritos
Modificar
Eliminar
Nueva carpeta
Mostrar favorito
Renombrar

Diálogo de favorito:
Agregar a favoritos
Favorito
Ruta
Carpeta de sistema
Nueva carpeta
Aceptar
Cancelar, s

Menú:
Opciones
Foro
Añadir el grupo QQ
Añadir el grupo WeiXin
Acerca de Extab
Salir

Opciones:
General
Ejecución automática
Mostrar favorito
Ejecución en segundo plano
Hacer doble clic en el espacio en blanco para ir a la ruta principal
Hacer clic en el espacio en blanco + tecla Ctrl para abrir una nueva pestaña
Hacer doble clic en una pestaña para cerrarla

Gestos de ratón
Mantener clic derecho y mover ratón hacia arriba para ir a la ruta principal
Mantener clic derecho y mover ratón a la izquierda para retroceder un nivel
Mantener clic derecho y mover ratón a la derecha para avanzar un nivel
Mantener clic derecho y mover ratón hacia abajo para abrir una nueva pestaña
Mantener clic derecho y mover ratón hacia Abajo y hacia la Derecha para cerrar la pestaña actual

Notificación de barra de tareas:
Abrir Extab
Opciones
Comentarios
Salir

Instalar:
Instalar ExTab:

Por favor, no cambie de ruta, porque ya está instalado.
Ejecución automática

Desinstalar:
Desinstalar
Cancelar
Guardar datos de usuario
```

**Comment by lily-debug** [comment]
Thank you  very very much！
1.0.0.18 released yesterday.
1.0.0.20 will support  English and Spanish. I will add them as soon as possible.

**Comment by lily-debug** [comment]
The version 1.0.0.20 supports English and Spanish, please download: https://github.com/lily-debug/extab/releases/download/1.0.0.20/mini_installer.exe , Please contact me if you have any questions

**Comment by c-sanchez** [comment]
Nice, thank you so much :D
There are several details in the translations that I would like to correct, I can see that there are several new lines, plus several minor details.

I have managed with some simple [ResourceHacker](http://www.angusj.com/resourcehacker/) scripts to extract and insert the strings again.
files: http://www.mediafire.com/file/sb5op9h9kw2kf90/reshack-extab.zip/file
Put these script/bat files with ResourceHacker.exe and extab.exe in same folder and run..

'**01 extract.bat**" to extract strings from **extrab.exe** as **StringTable.RC**

"**02 compile.bat**" to compile that **StringTable.RC** as **StringTable.res** binary file.

"**03 addoverwrite.bat**" to insert the **StringTable.res** binary file in **extrab**.

These are my updated strings using that "ResHack method" :P
I don't know if this is viable in any way for you, but well, something to start with at least heh.

A fun fact, I did  these script previously to translate [SwiftSearch](https://sourceforge.net/projects/swiftsearch/) (a nice alternative to "Everything")
https://sourceforge.net/p/swiftsearch/discussion/General/thread/4d97c51d/#cf0b

**Comment by lily-debug** [comment]
Thanks for your review.
I will update the new resources in next version.
